##4. CREATING NEW USER, ADDING EXISTED USER TO A GROUP, DELETE EXISTED USER
---
- name: Manage users on remote host
  hosts: dev
  user: ansible
  become: true
  gather_facts: false

  tasks:
    - name: Create a new user
      user:
        name: kamal
        password: "{{ 'vimal' | password_hash('sha512') }}"
        state: present
      # Create a new user with the name 'new_user' and set the password
    - name: Add an existing user to a group
      user:
        name: kamal
        groups: ec2-user
        append: yes
      # Add the existing user 'existing_user' to the group 'group_name'

    - name: Delete an existing user
      user:
        name: kamal
        state: absent
      # Delete the existing user 'existing_user' from the remote host
